var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+auto switch", {
    "+auto switch": function(url, host, scheme) {
        "use strict";
        if (/(?:^|\.)stackpathcdn\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)twitter\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)cms-twdigitalassets\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)v2ray\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)openai\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)sms-activate\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)jivo\.ru$/.test(host)) return "+proxy";
        if (/(?:^|\.)smsactivate\.s3\.eu-central-1\.amazonaws\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)maven-badges\.herokuapp\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)quora\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)jsdelivr\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)nioee\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)stripe\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)fontawesome\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)linuxmint\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)angelo\.org\.cn$/.test(host)) return "+proxy";
        if (/(?:^|\.)alicdn\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)v2ex\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)zaihuapan\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)mdict\.cn$/.test(host)) return "+proxy";
        if (/(?:^|\.)spring\.io$/.test(host)) return "+proxy";
        if (/(?:^|\.)tiqcdn\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)jquery\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)marketo\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)oracletutorial\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)chartio\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)cyberciti\.biz$/.test(host)) return "+proxy";
        if (/(?:^|\.)xda-developers\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)consensu\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)intellitxt\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)quantserve\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)pub\.network$/.test(host)) return "+proxy";
        if (/(?:^|\.)linux-apps\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)nr-data\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)pling\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)opendesktop\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)d33wubrfki0l68\.cloudfront\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)ubuntu-touch\.io$/.test(host)) return "+proxy";
        if (/(?:^|\.)renegade-project\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)clearbit\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)elastic\.co$/.test(host)) return "+proxy";
        if (/(?:^|\.)draculatheme\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)bootstrapcdn\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)darmau\.design$/.test(host)) return "+proxy";
        if (/(?:^|\.)bohan\.co$/.test(host)) return "+proxy";
        if (/(?:^|\.)aiursoft\.cn$/.test(host)) return "+proxy";
        if (/(?:^|\.)gravatar\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)iana\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)yadro\.ru$/.test(host)) return "+proxy";
        if (/(?:^|\.)booklist\.is$/.test(host)) return "+proxy";
        if (/(?:^|\.)libsolutions\.app$/.test(host)) return "+proxy";
        if (/(?:^|\.)z-lib\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)jp1lib\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)booksc\.xyz$/.test(host)) return "+proxy";
        if (/(?:^|\.)art1lib\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)art1lib\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)booksc\.me$/.test(host)) return "+proxy";
        if (/(?:^|\.)bookshome\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)1lib\.to$/.test(host)) return "+proxy";
        if (/(?:^|\.)booksc\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)bookshome\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)libsolutions\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)1lib\.education$/.test(host)) return "+proxy";
        if (/(?:^|\.)1lib\.limited$/.test(host)) return "+proxy";
        if (/(?:^|\.)b-ok\.global$/.test(host)) return "+proxy";
        if (/(?:^|\.)bookos-z1\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)3lib\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)b-ok\.as$/.test(host)) return "+proxy";
        if (/(?:^|\.)book4you\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)zlibcdn2\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)meomiao\.xyz$/.test(host)) return "+proxy";
        if (/(?:^|\.)singlelogin\.app$/.test(host)) return "+proxy";
        if (/(?:^|\.)zlibrary\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)1lib\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)b-ok\.asia$/.test(host)) return "+proxy";
        if (/(?:^|\.)1lib\.domains$/.test(host)) return "+proxy";
        if (/(?:^|\.)singlelogin\.me$/.test(host)) return "+proxy";
        if (/(?:^|\.)meomiao\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)imgur\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)v2ex\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)substack\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)techspot\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)jetbrains\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)chat-gpt-next-web\.vercel\.app$/.test(host)) return "+proxy";
        if (/(?:^|\.)poe\.com$/.test(host)) return "+proxy";
        if (/sharecuts\.cn$/.test(host)) return "+proxy";
        return "DIRECT";
    },
    "+proxy": function(url, host, scheme) {
        "use strict";
        if (/^127\.0\.0\.1$/.test(host) || /^::1$/.test(host) || /^localhost$/.test(host)) return "DIRECT";
        return "PROXY 127.0.0.1:7890";
    }
});